export const PASSION_DATA = [
    'photography',
    'hiking',
    'reading',
    'skincare',
    'karaoke',
    'gospel',
    'hip hop',
    'travelling',
    'arts and creativity',
    'reading',
    'singing',
    'running',
    'social media',
    'poetry',
    'theatre',
    'animal lover',
    'movies',
    'meditation',
    'foodie',
    'freelance',
    'shisha',
    'gym',
    'self care',
    'language',
    'spa',
    'walking',
    'spotify',
    'sushi',
    'sports',
    'k-pop',
    'wine',
    'tonic',
    'yoga',
    'sport',
    'dancing',
    'gardening',
    'fashion',
    'twitter',
    'discovering new things',
    'party',
    'weddings'

]